### ISSUE TITLE
Recommended section grid view error

### ISSUE THREAD

**Issue by blackPantherOS** [prateekmedia/Menu11#19]
[Previous error](https://github.com/prateekmedia/Menu11/issues/18) really solved, here is new issue after commit:

This error also solved `file:///[...].local/share/plasma/plasmoids/menu11/contents/ui/MainColumnItem.qml:177:9: Cannot assign to non-existent property "clearButtonShown"`

I get another issues in Menu11 "Recommend" section gridView on this Plasma version 

![blackPanther_20210717_121350](https://user-images.githubusercontent.com/12883566/126033776-001b882a-ee4a-4272-bc0b-e2c460a6f8f5.jpg)

I tried OnzeMenu and looks the girdview looks good
![blackPanther_20210717_122130](https://user-images.githubusercontent.com/12883566/126033958-ad21f4da-a833-4ffc-af78-3ce9864bfc55.jpg)

**Comment by prateekmedia** [comment]
Can you update the screenshot?

**Comment by prateekmedia** [comment]
Closing due to lack of response and info.

**Comment by blackPantherOS** [comment]
> Closing due to lack of response and info.
maybe tonight will have free time again, sorry, I'm very busy now
I will update our system and made new screenshots

**Comment by blackPantherOS** [comment]
Hello, I've updated from git and the previous issues (the non-existent propertys) does not exist you really fixed, and now anyone can load menu for use without crash.

New pictures of looks issues:

![image](https://user-images.githubusercontent.com/12883566/126462576-d3d5842e-8c66-488a-b6a7-c0d1955f9a6c.png)

All apps view (and "more" list is same as well)

![image](https://user-images.githubusercontent.com/12883566/126463037-4e8239bc-2f66-43c9-ad13-719fb501eca1.png)

**Comment by prateekmedia** [comment]
@blackPantherOS Can you checkout v7.0, maybe it will fix it.

**Comment by blackPantherOS** [comment]
> @blackPantherOS Can you checkout v7.0, maybe it will fix it.

Still exists :(

![image](https://user-images.githubusercontent.com/12883566/126863699-ee629d36-b63e-4e19-b8d1-21af96839b89.png)

and
![image](https://user-images.githubusercontent.com/12883566/126863776-6081ffb8-d0cd-4ce3-beb4-ce5e56ecd238.png)

**Comment by prateekmedia** [comment]
@blackPantherOS is your username visible to you?

**Comment by blackPantherOS** [comment]
> @blackPantherOS is your username visible to you?

Where? On your luncher or another launcher?  The full name of user are displayed on antoher luncher, like this:
![image](https://user-images.githubusercontent.com/12883566/126865174-32c2e888-2b4c-4225-9ac2-5c7f9625d96b.png)

**Comment by blackPantherOS** [comment]
Ok, I check your screenshot, and I understand your question. 
On Menu11 footer does not available user name or full name of user, and if I clicked to my user picture, opening systemsettings and not the user manager..

**Comment by prateekmedia** [comment]
Old version of plasma has too much bugs related to relative positioning and
all the errors you told are due to it, anchors.left or anchors.right.

Like for recommended grid it's due to the label being placed next to icon
using
anchors.left: icon.right

**Comment by blackPantherOS** [comment]
> Like for recommended grid it's due to the label being placed next to icon using https://github.com/prateekmedia/Menu11/blob/471c2c646dadde1f6f40ca9c82ae8daa953f6773/contents/ui/ItemGridDelegate.qml#L78

Your thinking way is good. I fixed this issue alerady (removed full "columnLayout {}"), look to my screenshot:

![image](https://user-images.githubusercontent.com/12883566/126898425-d41eec0c-6b38-4633-ba5d-d6cb9e2866a1.png)

**Comment by prateekmedia** [comment]
But this broken the look, the description should be below the title as win11 design. :(

**Comment by prateekmedia** [comment]
Ok I think I fixed it, can you checkout the latest version?

**Comment by blackPantherOS** [comment]
> Ok I think I fixed it, can you checkout the latest version?
Sorry if I'm late, we have was a long weekend

:( the issue still exists
![blackPanther_20210803_194419](https://user-images.githubusercontent.com/12883566/128061708-30446488-8939-4b87-8372-87c0a1e6d9f8.jpg)

**Comment by aufarijaal** [comment]
same issue here

**Comment by hd4y2t** [comment]
same issue 😞
